# ================================
# OhMyUniversity! - Mobile
# ================================

name: ohmyuniversity
description: "OhMyUniversity! mobile app from OhMyOpenSource!"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

# ================================
# Dependencies
# ================================
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Navigation ================================
  go_router: ^17.3.0

  # State Management + DI ================================
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

  # Network ================================
  dio: ^5.10.0

  # Auth SSO ================================
  flutter_appauth: ^12.0.1
  flutter_secure_storage: ^10.3.1

  # Models ================================
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Utils ================================
  url_launcher: ^6.3.1

  # Environment ================================
  envied: ^1.3.5

  # UI - Calendar ================================
  kalender: ^0.18.6

  # UI - Graphs ================================
  fl_chart: ^1.2.0

  # UI - Timeline ================================
  timelines_plus: ^2.0.0

  # UI - Loading ================================
  skeletonizer: ^2.1.3

  # UI - List Interactions ================================
  flutter_slidable: ^4.0.3

  # UI - Toast / Snackbar ================================
  toastification: ^3.2.0

  # UI - Animations ================================
  animations: ^2.0.11
  google_fonts: ^8.1.0
  lottie: ^3.3.1
  flutter_svg:
  lucide_icons_flutter: ^3.1.14+2


# ================================
# Dev Dependencies
# ================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Codegen ================================
  build_runner: ^2.4.15
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.3
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  envied_generator: ^1.3.5
  # custom_lint: ^0.8.1

  # Test ================================
  mockito: ^5.4.5

# ================================
# Flutter Config
# ================================
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/animations/
    - assets/animations/home/
    - assets/animations/onboarding/
    - assets/animations/orientation/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-VariableFont_wght.ttf

