sonar.projectKey=ohmyopensource_ohmyuniversity-mobile
sonar.organization=ohmyopensource
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Sources
sonar.sources=lib
sonar.tests=test

# Exclusions
sonar.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.gen.dart,\
  **/*.mocks.dart,\
  **/generated/**

sonar.coverage.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.gen.dart,\
  **/*.mocks.dart,\
  **/generated/**,\
  **/mocks/**,\
  **/*_mock_datasource.dart

sonar.cpd.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.gen.dart,\
  **/*.mocks.dart,\
  **/generated/**,\
  **/mocks/**,\
  **/*_mock_data.dart,\
  **/*_mock_datasource.dart,\
  lib/features/auth/data/constants/login_universities.dart,\
  lib/features/orientation/data/orientation_static_data.dart,\
  lib/features/orientation/presentation/pages/topics/**,\
  lib/**/data/models/**,\
  lib/config/theme/app_theme.dart

sonar.dart.lcov.reportPaths=coverage/lcov.info
