sonar.projectKey=ohmyopensource_ohmyuniversity-mobile
sonar.organization=ohmyopensource
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Sources
sonar.sources=lib
sonar.tests=test

# Exclusions
sonar.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.gen.dart,\
  **/*.mocks.dart,\
  **/generated/**

sonar.coverage.exclusions=\
  **/*.g.dart,\
  **/*.freezed.dart,\
  **/*.gen.dart,\
  **/*.mocks.dart,\
  **/generated/**

sonar.dart.lcov.reportPaths=coverage/lcov.info